services:
  - type: web
    name: fliff-ev-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 180
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: CACHE_TTL
        value: 1800
      - key: ODDS_API_KEY
        sync: false
